version: '3.6'

services:
    web:
        image: nginx-pisense
        container_name: nginx
        hostname: nginx-container
        tty: true
        build: ./
        networks:
            - default
        ports:
            - '0.0.0.0:80:80'
            - '0.0.0.0:443:443'
        volumes:
            - ./www/:/usr/share/nginx/html
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        # command: ['nginx', '-g', 'daemon off;']
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    db:
        image: mariadb:latest
        container_name: mariadb
        hostname: mariadb-container
        build: db/
        networks:
            - default
        ports:
            - '3306:3306'
    certbot:
        image: certbot/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
        volumes:
           - ./data/certbot/conf:/etc/letsencrypt
           - ./data/certbot/www:/var/www/certbot

volumes:
    www:

