version: '3.6'

services:
    web:
        image: nginx-pisense
        container_name: nginx
        hostname: nginx-container
        tty: true
        build: ./
        networks:
            - default
        ports:
            - '0.0.0.0:80:80'
            - '0.0.0.0:443:443'
        volumes:
            - ./www/:/usr/share/nginx/html
        command: [nginx, '-g', 'daemon off;']

volumes:
    www:
